#!/bin/bash

[ "$(uci -q get system.gatway.key)" != " " ] && exit 0
[ "$(uci -q get system.gatway.cl_ip)" != " " ] && exit 0
[ "$(uci -q get system.gatway.gw_ip)" != " " ] && exit 0

uci set system.gateway=gateway
uci set system.gateway.key=' '
uci set system.gateway.cl_ip=' '
uci set system.gateway.gw_ip=' '
uci commit

exit 0
