#!/bin/sh

uci -q batch <<-EOF >/dev/null
         delete ucitrack. at mm-cli[-1]
         add ucitrack mm-cli
         set ucitrack. at mm-cli[-1].init=mm-cli
         commit ucitrack
EOF

uci set system.gateway=gateway
uci set system.gateway.key=' '
uci set system.gateway.cl_ip=' '
uci set system.gateway.gw_ip=' '
rm -f /tmp/luci-indexcache
exit 0
