#!/bin/sh /etc/rc.common

START=91
STOP=85

USE_PROCD=1

start_service()
{
  [ -f /etc/uci-defaults/autoygg ] && ( . /etc/uci-defaults/autoygg )

  procd_open_instance
  procd_set_param respawn

  procd_set_param command /bin/ash -c "autoygg-client --useUCI --action=register"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

stop_service()
{
  killall autoygg-client
}

reload_service()
{
  restart
}

service_triggers()
{
  procd_add_reload_trigger autoygg
}
